name: pyinstaller build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
        cache-dependency-path: setup.py
    - run: "pip install pyinstaller"
    - run: "pip install -e .[dev]"
    - run: "pyinstaller --onefile -n guiltysync guiltysync/scripts/__init__.py"

    - name: Store pyinstaller output
      uses: actions/upload-artifact@v3
      with:
        name: pyinstaller-output
        path: dist/guiltysync.exe
