name: py2exe build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
    - run: "pip install .[dev]"
    - run: "python setup.py py2exe"
